import React, {Component} from 'react'
import {
    View,
    Image,
    TextInput,
    Keyboard,
    ScrollView,
    TouchableWithoutFeedback,
    TouchableOpacity,
    DeviceEventEmitter
} from 'react-native'

import {hradio,wradio} from '../../../radio'

export default class Goods extends Component{
    constructor(props){
	super(props)
    }
    render(){
	return(
		<View
	    style={{flex:1}}
		>
		<Image
	    source={require('./static/maingoods.png')}
	    style={{height:hradio*20,width:wradio*80,
		    margin:hradio*10
		   }}
		/>
		<ScrollView
	    style={{flex:1}}
		>
		<TouchableOpacity
	    onPress={()=>{this.props.navigate('S_detail')}}
		>
		<Image
	    source={require('./static/goods1.png')}
	    style={{height:hradio*193,width:wradio*720}}
		/>
		</TouchableOpacity>
		<TouchableOpacity
	onPress={()=>this.props.navigate('S_detail')}
		>		
		<Image
	    source={require('./static/goods2.png')}
	    style={{height:hradio*193,width:wradio*720}}
		/>
		</TouchableOpacity>
		<TouchableOpacity
	onPress={()=>this.props.navigate('S_detail')}
		>		
		<Image
	    source={require('./static/goods3.png')}
	    style={{height:hradio*193,width:wradio*720}}
		/>
		</TouchableOpacity>
		<TouchableOpacity
	onPress={()=>this.props.navigate('S_detail')}
		>				
		<Image
	    source={require('./static/goods4.png')}
	    style={{height:hradio*193,width:wradio*720}}
		/>
		</TouchableOpacity>		
		</ScrollView>
		<Image
	    source={require('./static/foot.png')}
	    style={{
		height:hradio*97,width:wradio*720,
		alignItems:'center',flexDirection:'row',alignSelf:'flex-end'
		   }}
		>
		<Image
	    source={require('./static/star.png')}
	    style={{marginLeft:wradio*30,height:hradio*65,width:wradio*40}}
		/>
		<Image
	    source={require('./static/cart.png')}
	    style={{marginLeft:wradio*30,height:hradio*50,width:wradio*56}}
		/>
		<TouchableOpacity
	    style={{marginLeft:wradio*365}}
	    onPress={()=>{
		this.props.navigate('GoOrder')
	    }}
		>
		<Image
	    source={require('./static/gobill.png')}
	    style={{height:hradio*96,width:wradio*200}}
		/>
		</TouchableOpacity>		
		</Image>
		</View>
	)
    }
}
